test:
	g++ test.cpp -std=c++17 -DTEST -O2
	./a.out


clear:
	rm ./a.out


# написать обертку, чтобы можно было 
# передавать аргументы в make команды
# По типу:
# > make x a1 a2
#   x: <- ищем
#      scjm [1] sdcdsc  -  заменяем, путем
# 	   ssc  [2] dv fdv     создания нового Makefil-а